Repository cse110-sp21-group32/cse110-sp21-group32, pull requests merged in 2021-06, with the labels that each got.

#39 Date selector
  .gitignore
  sources/components/bulletEditorPage.js
  sources/components/bulletEntry.js
  sources/components/categoryEditorPage.js
  sources/components/categoryEntry.js
  sources/components/dateEntry.js
  sources/index.html
  sources/scripts/router.js
  sources/scripts/script.js
  sources/scripts/storage.js
  sources/styles.css
Labels: enhancement

#58 Comments
  sources/components/bulletEditorPage.js
  sources/components/bulletEntry.js
  sources/components/categoryEditorPage.js
  sources/components/categoryEntry.js
  sources/components/dateEntry.js
  sources/scripts/script.js
  sources/scripts/storage.js
Labels: documentation

#59 Inline editor
  admin/meetings/060721-retrospective.md
  admin/meetings/060721-sprint-3-review.md
  admin/meetings/Assets/FinalRetro.png
  index.html
  sources/components/bulletEditorPage.js
  sources/components/bulletEntry.js
  sources/components/categoryEntry.js
  sources/components/dateEntry.js
  sources/scripts/script.js
  sources/scripts/storage.js
  sources/styles.css
Labels: enhancement

#61 Inline editor
  sources/components/bulletEditorPage.js
  sources/components/bulletEntry.js
  sources/components/categoryEditorPage.js
  sources/components/txt
  sources/scripts/router.js
  sources/scripts/script.js
  sources/scripts/storage.js
Labels: enhancement

#62 Unit testing
  README.md
  admin/style-guide.md
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/index.html
  coverage/lcov-report/storage.js.html
  coverage/lcov.info
  package-lock.json
  package.json
  sources/scripts/script.js
  sources/scripts/storage.js
  test/coverage.md
  test/e2e/bullet.test.js
  test/e2e/category.test.js
  test/testing.md
  test/unit/bulletEditorPage.test.js
  test/unit/categoryEditorPage.test.js
  test/unit/script.test.js
  test/unit/storage.test.js
Labels: testing
